server:
  port: 8000

spring:
  application:
    name: sonic-gen
  profiles:
    active: dev
    include: init
  http: 
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update


  web:
    argument-trim: true
    argument-blank-to-null: true


